version: "3.8"

services:

  nuxt-service:
    build:
      context: ./micro-frontend/nuxt-app-service
      dockerfile: Dockerfile
    container_name: nuxt-service
    image: nuxt-service:latest
    ports:
    - "3032:3000"
    networks:
      - micro-frontend-network
    volumes:
      - ./micro-frontend/nuxt-app-service:/src/app
      - /src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HMR_HOST=host.docker.internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 5s
      timeout: 3s
      retries: 5

  next-service:
    build:
      context: ./micro-frontend/next-service
      dockerfile: Dockerfile
    container_name: next-service
    image: next-service:latest
    ports:
    - "3031:3000"
    networks:
      - micro-frontend-network
    volumes:
      - ./micro-frontend/next-service:/src/app
      - /src/app/node_modules
    environment:
        - CHOKIDAR_USEPOLLING=true  # Untuk file watching di Docker
        - WATCHPACK_POLLING=true    # Alternative untuk file watching
        - NODE_ENV=development
        - HOST=0.0.0.0
        - PORT=3031
    stdin_open: true
    tty: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 5s
      timeout: 3s
      retries: 5
    
  auth-service-laravel:
    build:
      context: ./micro-service/laravel-service
      dockerfile: ./docker/workspace/development/Dockerfile
      target: development
    container_name: auth-service-laravel
    image: auth-service-laravel:latest
    # ports:
    # - "127.0.0.1:8080:3000" 
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_DEBUG=${APP_DEBUG:-true}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-micro-service}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-1215161}
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./micro-service/laravel-service:/var/www
    networks:
      - micro-service-network

  express-service:
    build:
      context: ./micro-service/express-service
      dockerfile: Dockerfile
    container_name: express-service
    image: express-service:latest
    ports:
    - "3000:3000" 
    depends_on:
      - auth-service-laravel
    networks:
      - micro-service-network
    volumes:
      - ./micro-service/express-service:/src/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      timeout: 3s
      retries: 5

  mysql:
    image: mysql:8
    container_name: laravel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-1215161}
      MYSQL_DATABASE: ${DB_DATABASE:-micro-service}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - micro-service-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD:-1215161}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  nginx-laravel:
    build: ./micro-service/laravel-service/docker/nginx/development
    container_name: nginx-laravel
    image: nginx-laravel:latest
    ports:
    - "8000:80" 
    depends_on:
      - auth-service-laravel
    networks:
      - micro-service-network
    healthcheck:
      test: curl -f http://localhost || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      
  gateway-nginx-backend:
    build: ./nginx-gateway-backend
    container_name: gateway-nginx-backend
    image: gateway-nginx-backend:latest
    ports:
      - "8080:80"
    depends_on:
      - auth-service-laravel
      - express-service
      - nginx-laravel
    networks:
      - micro-service-network
    restart: always

  gateway-nginx-frontend:
    build: ./nginx-gateway-frontend
    container_name: gateway-nginx-frontend
    image: gateway-nginx-frontend:latest
    ports:
      - "8083:80"
    depends_on:
      - nuxt-service
    networks:
      - micro-frontend-network
    restart: always


networks:
  micro-service-network:
    driver: bridge
  micro-frontend-network:
    driver: bridge

volumes:
  mysql_data: